apiVersion: apps/v1
kind: Deployment
metadata:
  name: studynotion-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: studynotion-backend
  template:
    metadata:
      labels:
        app: studynotion-backend
    spec:
      containers:
      - name: backend
        # Make sure this is your correct username!
        image: shibilbasithcp/studynotion-backend:latest
        ports:
        - containerPort: 4000
        envFrom:
        - secretRef:
            name: backend-secrets
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: studynotion-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
  type: ClusterIP
---
# ------------------------------------------------------
# NEW: BACKEND ROUTE (Exposes API to the Internet)
# ------------------------------------------------------
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: studynotion-backend-route
spec:
  to:
    kind: Service
    name: backend-service
  port:
    targetPort: 4000
  tls:
    termination: edge