apiVersion: apps/v1
kind: Deployment
metadata:
  name: studynotion-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: studynotion-frontend
  template:
    metadata:
      labels:
        app: studynotion-frontend
    spec:
      containers:
      - name: frontend
        image: shibilbasithcp/studynotion-frontend:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: studynotion-frontend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
---
# OPENSHIFT ROUTE (Replaces Ingress)
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: studynotion-frontend-route
spec:
  to:
    kind: Service
    name: frontend-service
  port:
    targetPort: 8080
  tls:
    termination: edge